# using when condition

- name: conditions
  hosts: localhost
  tasks:
    - name: check if user exists or not
      ansible.builtin.command: id roboshop # passing command
      register: user # storing output of the command in user variable
      ignore_errors: true # ansible wont terminate the code executuion even if there are few errors
    - name : printing the variable -value
      ansible.builtin.debug:
        msg: "user is : {{user}}"

    - name: printing exit status 
      ansible.builtin.debug:
        msg: "exit status is: {{user.rc}}"    # exit status is 1 if user is not present

    - name: create user 
      ansible.builtin.user:
        name: roboshop
      when: user.rc !=0  # if rc is 1 then create user   
