# installing few packages and uninstalling few

- name: installing packages with loop
  hosts: localhost
  become: true
  tasks: 
    - name: install packages
      ansible.builtin.package:
        name: "{{item.name}}"
        state: "{{item.state}}"
      loop:
        - {name: 'git', state: 'present'}
        - {name: 'postfix', state: 'absent'}
        - {name: 'mysql', state: 'absent'}
        - {name: 'nginx', state: 'present'}

    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
